server:
  port: 8010

spring:
  profiles:
    #    active: git

    # change config can not effect immediately， need to reboot server
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
        git:
          skip-ssl-validation: true
          uri: https://github.com/jianane/config_server
