server:
  port: 8010

spring:
  profiles:
        active: git

    # change config can not effect immediately， need to reboot server
#    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:shared, classpath:share
        git:
          skip-ssl-validation: true
          uri: file://E:/workspace_sc/config_server #从本地取 添加到git的会强制回退到和git服务器相同的版本，没添加的不会，并且随意修改也可以生效（比native好用）
#          uri: https://github.com/jianane/config_server
          search-paths: src/main/resources/shared, src/main/resources/share
